/**
 * Original abstract web/network geometry (CLAUDE.md §4 "The Web Is the Pipeline",
 * decision 12; PLANNING.md §5.4). Pure and seeded so server and client render
 * identically — no `Math.random()` at render time, no hydration mismatches
 * (CLAUDE.md §6). Radial spokes from a hub; concentric "rings" are drawn as slightly
 * sagging arcs bowed toward the hub rather than perfect polygons, which is what reads
 * as a web instead of a target or a wireframe globe.
 *
 * This is code, not imported artwork (CLAUDE.md §4 "Spider-inspiration guardrails" —
 * web geometry must be original and generated by code).
 */

export interface WebNode {
  id: string;
  x: number;
  y: number;
  /** 0 = the hub itself. */
  ring: number;
  /** -1 for the hub; otherwise the spoke index this node sits on. */
  spoke: number;
}

export interface WebGeometry {
  size: number;
  hub: { x: number; y: number };
  nodes: WebNode[];
  /** One SVG path `d` string per spoke, hub to outermost ring. */
  spokePaths: string[];
  /** One closed SVG path `d` string per concentric ring. */
  ringPaths: string[];
}

export interface GenerateWebOptions {
  /** Any integer. Same seed -> identical geometry, every time, on server or client. */
  seed: number;
  /** Number of spokes radiating from the hub. */
  radials: number;
  /** Number of concentric rings. */
  rings: number;
  /** Square SVG viewBox size in user units. */
  size?: number;
  /** 0-1: how far each ring segment bows toward the hub instead of a straight line. */
  sag?: number;
  /** 0-1: how much randomness to apply to spoke angle and ring radius. */
  jitter?: number;
}

/** A tiny deterministic PRNG (mulberry32) — no dependency needed for this. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function generateWeb(options: GenerateWebOptions): WebGeometry {
  const { seed, radials, rings, size = 600, sag = 0.12, jitter = 0.06 } = options;
  const rand = mulberry32(seed);
  const cx = size / 2;
  const cy = size / 2;
  const maxRadius = size / 2;

  const angles: number[] = Array.from({ length: radials }, (_, i) => {
    const base = (i / radials) * Math.PI * 2;
    const wobble = (rand() - 0.5) * jitter * (Math.PI / radials);
    return base + wobble;
  });

  const nodes: WebNode[] = [{ id: "hub", x: cx, y: cy, ring: 0, spoke: -1 }];

  const pointsByRing: { x: number; y: number }[][] = Array.from({ length: rings }, (_, ringIndex) => {
    const baseRadius = ((ringIndex + 1) / rings) * maxRadius;
    return angles.map((angle, spokeIndex) => {
      const radius = baseRadius * (1 + (rand() - 0.5) * jitter * 0.35);
      const x = cx + Math.cos(angle) * radius;
      const y = cy + Math.sin(angle) * radius;
      nodes.push({ id: `r${ringIndex + 1}-s${spokeIndex}`, x, y, ring: ringIndex + 1, spoke: spokeIndex });
      return { x, y };
    });
  });

  const spokePaths = angles.map((_, spokeIndex) => {
    let d = `M ${cx} ${cy}`;
    for (let ringIndex = 0; ringIndex < rings; ringIndex++) {
      const p = pointsByRing[ringIndex][spokeIndex];
      d += ` L ${p.x.toFixed(2)} ${p.y.toFixed(2)}`;
    }
    return d;
  });

  const ringPaths = pointsByRing.map((points) => {
    let d = `M ${points[0].x.toFixed(2)} ${points[0].y.toFixed(2)}`;
    for (let i = 0; i < points.length; i++) {
      const a = points[i];
      const b = points[(i + 1) % points.length];
      const midX = (a.x + b.x) / 2;
      const midY = (a.y + b.y) / 2;
      const ctrlX = midX + (cx - midX) * sag;
      const ctrlY = midY + (cy - midY) * sag;
      d += ` Q ${ctrlX.toFixed(2)} ${ctrlY.toFixed(2)} ${b.x.toFixed(2)} ${b.y.toFixed(2)}`;
    }
    return d + " Z";
  });

  return { size, hub: { x: cx, y: cy }, nodes, spokePaths, ringPaths };
}
